# Generated by Django 4.2.15 on 2024-08-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_recommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
